'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.5485.
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DecodificarClaveSoap", [Namespace]:="http://BidfEncripta/desEncripta")>  _
    Partial Public Class DecodificarClave
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private DecodificaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CodificarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BIFUtils.My.MySettings.Default.BIFUtils_WebReference_DecodificarClave
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event DecodificaCompleted As DecodificaCompletedEventHandler
        
        '''<remarks/>
        Public Event CodificarCompleted As CodificarCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BidfEncripta/desEncripta/Decodifica", RequestNamespace:="http://BidfEncripta/desEncripta", ResponseNamespace:="http://BidfEncripta/desEncripta", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Decodifica(ByVal a_codificar As String) As String
            Dim results() As Object = Me.Invoke("Decodifica", New Object() {a_codificar})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DecodificaAsync(ByVal a_codificar As String)
            Me.DecodificaAsync(a_codificar, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DecodificaAsync(ByVal a_codificar As String, ByVal userState As Object)
            If (Me.DecodificaOperationCompleted Is Nothing) Then
                Me.DecodificaOperationCompleted = AddressOf Me.OnDecodificaOperationCompleted
            End If
            Me.InvokeAsync("Decodifica", New Object() {a_codificar}, Me.DecodificaOperationCompleted, userState)
        End Sub
        
        Private Sub OnDecodificaOperationCompleted(ByVal arg As Object)
            If (Not (Me.DecodificaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DecodificaCompleted(Me, New DecodificaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BidfEncripta/desEncripta/Codificar", RequestNamespace:="http://BidfEncripta/desEncripta", ResponseNamespace:="http://BidfEncripta/desEncripta", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Codificar(ByVal a_codificar As String) As String
            Dim results() As Object = Me.Invoke("Codificar", New Object() {a_codificar})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CodificarAsync(ByVal a_codificar As String)
            Me.CodificarAsync(a_codificar, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CodificarAsync(ByVal a_codificar As String, ByVal userState As Object)
            If (Me.CodificarOperationCompleted Is Nothing) Then
                Me.CodificarOperationCompleted = AddressOf Me.OnCodificarOperationCompleted
            End If
            Me.InvokeAsync("Codificar", New Object() {a_codificar}, Me.CodificarOperationCompleted, userState)
        End Sub
        
        Private Sub OnCodificarOperationCompleted(ByVal arg As Object)
            If (Not (Me.CodificarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CodificarCompleted(Me, New CodificarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub DecodificaCompletedEventHandler(ByVal sender As Object, ByVal e As DecodificaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DecodificaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub CodificarCompletedEventHandler(ByVal sender As Object, ByVal e As CodificarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CodificarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
