'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1820
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DataSetDocumentoCobranza"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DataSetDocumentoCobranza
    Inherits Global.System.Data.DataSet
    
    Private tableDatosCobranza As DatosCobranzaDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DatosCobranza")) Is Nothing) Then
                MyBase.Tables.Add(New DatosCobranzaDataTable(ds.Tables("DatosCobranza")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DatosCobranza() As DatosCobranzaDataTable
        Get
            Return Me.tableDatosCobranza
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DataSetDocumentoCobranza = CType(MyBase.Clone,DataSetDocumentoCobranza)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("DatosCobranza")) Is Nothing) Then
                MyBase.Tables.Add(New DatosCobranzaDataTable(ds.Tables("DatosCobranza")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableDatosCobranza = CType(MyBase.Tables("DatosCobranza"),DatosCobranzaDataTable)
        If (initTable = true) Then
            If (Not (Me.tableDatosCobranza) Is Nothing) Then
                Me.tableDatosCobranza.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DataSetDocumentoCobranza"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DataSetDocumentoCobranza.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableDatosCobranza = New DatosCobranzaDataTable
        MyBase.Tables.Add(Me.tableDatosCobranza)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeDatosCobranza() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DataSetDocumentoCobranza = New DataSetDocumentoCobranza
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub DatosCobranzaRowChangeEventHandler(ByVal sender As Object, ByVal e As DatosCobranzaRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class DatosCobranzaDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnDLACC As Global.System.Data.DataColumn
        
        Private columnCUSNA1 As Global.System.Data.DataColumn
        
        Private columnDIRECCION As Global.System.Data.DataColumn
        
        Private columnCUSCTY As Global.System.Data.DataColumn
        
        Private columnCUSZPC As Global.System.Data.DataColumn
        
        Private columnBRNNUM As Global.System.Data.DataColumn
        
        Private columnBRNNME As Global.System.Data.DataColumn
        
        Private columnBRNADR As Global.System.Data.DataColumn
        
        Private columnBRNPHN As Global.System.Data.DataColumn
        
        Private columnDLNCC As Global.System.Data.DataColumn
        
        Private columnDLVCA As Global.System.Data.DataColumn
        
        Private columnDLVCM As Global.System.Data.DataColumn
        
        Private columnDLVCD As Global.System.Data.DataColumn
        
        Private columnDLCCY As Global.System.Data.DataColumn
        
        Private columnDLEIC As Global.System.Data.DataColumn
        
        Private columnCIUDAG As Global.System.Data.DataColumn
        
        Private columnPROVAG As Global.System.Data.DataColumn
        
        Private columnDEPTAG As Global.System.Data.DataColumn
        
        Private columnHORAAG As Global.System.Data.DataColumn
        
        Private columnData As Global.System.Data.DataColumn
        
        Private columnCUSFNA As Global.System.Data.DataColumn
        
        Private columnCUSLN1 As Global.System.Data.DataColumn
        
        Private columnCUSLN2 As Global.System.Data.DataColumn
        
        Private columnCUSSEX As Global.System.Data.DataColumn
        
        Private columnSIGN1NAME As Global.System.Data.DataColumn
        
        Private columnSIGN2NAME As Global.System.Data.DataColumn
        
        Private columnSIGN1POSITION As Global.System.Data.DataColumn
        
        Private columnSIGN2POSITION As Global.System.Data.DataColumn
        
        Private columnSIGN1DATA As Global.System.Data.DataColumn
        
        Private columnSIGN2DATA As Global.System.Data.DataColumn
        
        Private columnDLEAEN As Global.System.Data.DataColumn
        
        Private columnDLEMEN As Global.System.Data.DataColumn
        
        Private columnDLEDEN As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "DatosCobranza"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLACCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLACC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSNA1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSNA1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DIRECCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDIRECCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSCTYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSCTY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSZPCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSZPC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BRNNUMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBRNNUM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BRNNMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBRNNME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BRNADRColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBRNADR
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BRNPHNColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBRNPHN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLNCCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLNCC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLVCAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLVCA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLVCMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLVCM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLVCDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLVCD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLCCYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLCCY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLEICColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLEIC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CIUDAGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCIUDAG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PROVAGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPROVAG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DEPTAGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDEPTAG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property HORAAGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAAG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnData
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSFNAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSFNA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSLN1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSLN1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSLN2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSLN2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CUSSEXColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUSSEX
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SIGN1NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSIGN1NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SIGN2NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSIGN2NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SIGN1POSITIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSIGN1POSITION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SIGN2POSITIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSIGN2POSITION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SIGN1DATAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSIGN1DATA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SIGN2DATAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSIGN2DATA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLEAENColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLEAEN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLEMENColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLEMEN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DLEDENColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDLEDEN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As DatosCobranzaRow
            Get
                Return CType(Me.Rows(index),DatosCobranzaRow)
            End Get
        End Property
        
        Public Event DatosCobranzaRowChanging As DatosCobranzaRowChangeEventHandler
        
        Public Event DatosCobranzaRowChanged As DatosCobranzaRowChangeEventHandler
        
        Public Event DatosCobranzaRowDeleting As DatosCobranzaRowChangeEventHandler
        
        Public Event DatosCobranzaRowDeleted As DatosCobranzaRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddDatosCobranzaRow(ByVal row As DatosCobranzaRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddDatosCobranzaRow( _
                    ByVal DLACC As Decimal,  _
                    ByVal CUSNA1 As String,  _
                    ByVal DIRECCION As String,  _
                    ByVal CUSCTY As String,  _
                    ByVal CUSZPC As String,  _
                    ByVal BRNNUM As Decimal,  _
                    ByVal BRNNME As String,  _
                    ByVal BRNADR As String,  _
                    ByVal BRNPHN As Decimal,  _
                    ByVal DLNCC As String,  _
                    ByVal DLVCA As Decimal,  _
                    ByVal DLVCM As Decimal,  _
                    ByVal DLVCD As Decimal,  _
                    ByVal DLCCY As String,  _
                    ByVal DLEIC As Decimal,  _
                    ByVal CIUDAG As String,  _
                    ByVal PROVAG As String,  _
                    ByVal DEPTAG As String,  _
                    ByVal HORAAG As String,  _
                    ByVal Data As String,  _
                    ByVal CUSFNA As String,  _
                    ByVal CUSLN1 As String,  _
                    ByVal CUSLN2 As String,  _
                    ByVal CUSSEX As String,  _
                    ByVal SIGN1NAME As String,  _
                    ByVal SIGN2NAME As String,  _
                    ByVal SIGN1POSITION As String,  _
                    ByVal SIGN2POSITION As String,  _
                    ByVal SIGN1DATA() As Byte,  _
                    ByVal SIGN2DATA() As Byte,  _
                    ByVal DLEAEN As Decimal,  _
                    ByVal DLEMEN As Decimal,  _
                    ByVal DLEDEN As Decimal) As DatosCobranzaRow
            Dim rowDatosCobranzaRow As DatosCobranzaRow = CType(Me.NewRow,DatosCobranzaRow)
            Dim columnValuesArray() As Object = New Object() {DLACC, CUSNA1, DIRECCION, CUSCTY, CUSZPC, BRNNUM, BRNNME, BRNADR, BRNPHN, DLNCC, DLVCA, DLVCM, DLVCD, DLCCY, DLEIC, CIUDAG, PROVAG, DEPTAG, HORAAG, Data, CUSFNA, CUSLN1, CUSLN2, CUSSEX, SIGN1NAME, SIGN2NAME, SIGN1POSITION, SIGN2POSITION, SIGN1DATA, SIGN2DATA, DLEAEN, DLEMEN, DLEDEN}
            rowDatosCobranzaRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowDatosCobranzaRow)
            Return rowDatosCobranzaRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As DatosCobranzaDataTable = CType(MyBase.Clone,DatosCobranzaDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New DatosCobranzaDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnDLACC = MyBase.Columns("DLACC")
            Me.columnCUSNA1 = MyBase.Columns("CUSNA1")
            Me.columnDIRECCION = MyBase.Columns("DIRECCION")
            Me.columnCUSCTY = MyBase.Columns("CUSCTY")
            Me.columnCUSZPC = MyBase.Columns("CUSZPC")
            Me.columnBRNNUM = MyBase.Columns("BRNNUM")
            Me.columnBRNNME = MyBase.Columns("BRNNME")
            Me.columnBRNADR = MyBase.Columns("BRNADR")
            Me.columnBRNPHN = MyBase.Columns("BRNPHN")
            Me.columnDLNCC = MyBase.Columns("DLNCC")
            Me.columnDLVCA = MyBase.Columns("DLVCA")
            Me.columnDLVCM = MyBase.Columns("DLVCM")
            Me.columnDLVCD = MyBase.Columns("DLVCD")
            Me.columnDLCCY = MyBase.Columns("DLCCY")
            Me.columnDLEIC = MyBase.Columns("DLEIC")
            Me.columnCIUDAG = MyBase.Columns("CIUDAG")
            Me.columnPROVAG = MyBase.Columns("PROVAG")
            Me.columnDEPTAG = MyBase.Columns("DEPTAG")
            Me.columnHORAAG = MyBase.Columns("HORAAG")
            Me.columnData = MyBase.Columns("Data")
            Me.columnCUSFNA = MyBase.Columns("CUSFNA")
            Me.columnCUSLN1 = MyBase.Columns("CUSLN1")
            Me.columnCUSLN2 = MyBase.Columns("CUSLN2")
            Me.columnCUSSEX = MyBase.Columns("CUSSEX")
            Me.columnSIGN1NAME = MyBase.Columns("SIGN1NAME")
            Me.columnSIGN2NAME = MyBase.Columns("SIGN2NAME")
            Me.columnSIGN1POSITION = MyBase.Columns("SIGN1POSITION")
            Me.columnSIGN2POSITION = MyBase.Columns("SIGN2POSITION")
            Me.columnSIGN1DATA = MyBase.Columns("SIGN1DATA")
            Me.columnSIGN2DATA = MyBase.Columns("SIGN2DATA")
            Me.columnDLEAEN = MyBase.Columns("DLEAEN")
            Me.columnDLEMEN = MyBase.Columns("DLEMEN")
            Me.columnDLEDEN = MyBase.Columns("DLEDEN")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnDLACC = New Global.System.Data.DataColumn("DLACC", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLACC)
            Me.columnCUSNA1 = New Global.System.Data.DataColumn("CUSNA1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSNA1)
            Me.columnDIRECCION = New Global.System.Data.DataColumn("DIRECCION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDIRECCION)
            Me.columnCUSCTY = New Global.System.Data.DataColumn("CUSCTY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSCTY)
            Me.columnCUSZPC = New Global.System.Data.DataColumn("CUSZPC", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSZPC)
            Me.columnBRNNUM = New Global.System.Data.DataColumn("BRNNUM", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBRNNUM)
            Me.columnBRNNME = New Global.System.Data.DataColumn("BRNNME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBRNNME)
            Me.columnBRNADR = New Global.System.Data.DataColumn("BRNADR", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBRNADR)
            Me.columnBRNPHN = New Global.System.Data.DataColumn("BRNPHN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBRNPHN)
            Me.columnDLNCC = New Global.System.Data.DataColumn("DLNCC", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLNCC)
            Me.columnDLVCA = New Global.System.Data.DataColumn("DLVCA", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLVCA)
            Me.columnDLVCM = New Global.System.Data.DataColumn("DLVCM", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLVCM)
            Me.columnDLVCD = New Global.System.Data.DataColumn("DLVCD", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLVCD)
            Me.columnDLCCY = New Global.System.Data.DataColumn("DLCCY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLCCY)
            Me.columnDLEIC = New Global.System.Data.DataColumn("DLEIC", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLEIC)
            Me.columnCIUDAG = New Global.System.Data.DataColumn("CIUDAG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCIUDAG)
            Me.columnPROVAG = New Global.System.Data.DataColumn("PROVAG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPROVAG)
            Me.columnDEPTAG = New Global.System.Data.DataColumn("DEPTAG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDEPTAG)
            Me.columnHORAAG = New Global.System.Data.DataColumn("HORAAG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAAG)
            Me.columnData = New Global.System.Data.DataColumn("Data", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnData)
            Me.columnCUSFNA = New Global.System.Data.DataColumn("CUSFNA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSFNA)
            Me.columnCUSLN1 = New Global.System.Data.DataColumn("CUSLN1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSLN1)
            Me.columnCUSLN2 = New Global.System.Data.DataColumn("CUSLN2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSLN2)
            Me.columnCUSSEX = New Global.System.Data.DataColumn("CUSSEX", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUSSEX)
            Me.columnSIGN1NAME = New Global.System.Data.DataColumn("SIGN1NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSIGN1NAME)
            Me.columnSIGN2NAME = New Global.System.Data.DataColumn("SIGN2NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSIGN2NAME)
            Me.columnSIGN1POSITION = New Global.System.Data.DataColumn("SIGN1POSITION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSIGN1POSITION)
            Me.columnSIGN2POSITION = New Global.System.Data.DataColumn("SIGN2POSITION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSIGN2POSITION)
            Me.columnSIGN1DATA = New Global.System.Data.DataColumn("SIGN1DATA", GetType(Byte()), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSIGN1DATA)
            Me.columnSIGN2DATA = New Global.System.Data.DataColumn("SIGN2DATA", GetType(Byte()), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSIGN2DATA)
            Me.columnDLEAEN = New Global.System.Data.DataColumn("DLEAEN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLEAEN)
            Me.columnDLEMEN = New Global.System.Data.DataColumn("DLEMEN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLEMEN)
            Me.columnDLEDEN = New Global.System.Data.DataColumn("DLEDEN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDLEDEN)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewDatosCobranzaRow() As DatosCobranzaRow
            Return CType(Me.NewRow,DatosCobranzaRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New DatosCobranzaRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(DatosCobranzaRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DatosCobranzaRowChangedEvent) Is Nothing) Then
                RaiseEvent DatosCobranzaRowChanged(Me, New DatosCobranzaRowChangeEvent(CType(e.Row,DatosCobranzaRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DatosCobranzaRowChangingEvent) Is Nothing) Then
                RaiseEvent DatosCobranzaRowChanging(Me, New DatosCobranzaRowChangeEvent(CType(e.Row,DatosCobranzaRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DatosCobranzaRowDeletedEvent) Is Nothing) Then
                RaiseEvent DatosCobranzaRowDeleted(Me, New DatosCobranzaRowChangeEvent(CType(e.Row,DatosCobranzaRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DatosCobranzaRowDeletingEvent) Is Nothing) Then
                RaiseEvent DatosCobranzaRowDeleting(Me, New DatosCobranzaRowChangeEvent(CType(e.Row,DatosCobranzaRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveDatosCobranzaRow(ByVal row As DatosCobranzaRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DataSetDocumentoCobranza = New DataSetDocumentoCobranza
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "DatosCobranzaDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class DatosCobranzaRow
        Inherits Global.System.Data.DataRow
        
        Private tableDatosCobranza As DatosCobranzaDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableDatosCobranza = CType(Me.Table,DatosCobranzaDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLACC() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLACCColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLACC' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLACCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSNA1() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSNA1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSNA1' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSNA1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DIRECCION() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DIRECCIONColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DIRECCION' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DIRECCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSCTY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSCTYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSCTY' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSCTYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSZPC() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSZPCColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSZPC' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSZPCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BRNNUM() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.BRNNUMColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BRNNUM' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.BRNNUMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BRNNME() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.BRNNMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BRNNME' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.BRNNMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BRNADR() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.BRNADRColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BRNADR' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.BRNADRColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BRNPHN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.BRNPHNColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BRNPHN' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.BRNPHNColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLNCC() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLNCCColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLNCC' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLNCCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLVCA() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLVCAColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLVCA' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLVCAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLVCM() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLVCMColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLVCM' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLVCMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLVCD() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLVCDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLVCD' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLVCDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLCCY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLCCYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLCCY' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLCCYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLEIC() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLEICColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLEIC' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLEICColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CIUDAG() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CIUDAGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CIUDAG' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CIUDAGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PROVAG() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.PROVAGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PROVAG' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.PROVAGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DEPTAG() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DEPTAGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DEPTAG' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DEPTAGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HORAAG() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.HORAAGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAAG' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.HORAAGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Data() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DataColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Data' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DataColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSFNA() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSFNAColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSFNA' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSFNAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSLN1() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSLN1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSLN1' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSLN1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSLN2() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSLN2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSLN2' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSLN2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CUSSEX() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.CUSSEXColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CUSSEX' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.CUSSEXColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SIGN1NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.SIGN1NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SIGN1NAME' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.SIGN1NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SIGN2NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.SIGN2NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SIGN2NAME' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.SIGN2NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SIGN1POSITION() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.SIGN1POSITIONColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SIGN1POSITION' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.SIGN1POSITIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SIGN2POSITION() As String
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.SIGN2POSITIONColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SIGN2POSITION' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.SIGN2POSITIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SIGN1DATA() As Byte()
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.SIGN1DATAColumn),Byte())
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SIGN1DATA' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.SIGN1DATAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SIGN2DATA() As Byte()
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.SIGN2DATAColumn),Byte())
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SIGN2DATA' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.SIGN2DATAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLEAEN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLEAENColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLEAEN' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLEAENColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLEMEN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLEMENColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLEMEN' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLEMENColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DLEDEN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDatosCobranza.DLEDENColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DLEDEN' in table 'DatosCobranza' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDatosCobranza.DLEDENColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLACCNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLACCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLACCNull()
            Me(Me.tableDatosCobranza.DLACCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSNA1Null() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSNA1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSNA1Null()
            Me(Me.tableDatosCobranza.CUSNA1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDIRECCIONNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DIRECCIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDIRECCIONNull()
            Me(Me.tableDatosCobranza.DIRECCIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSCTYNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSCTYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSCTYNull()
            Me(Me.tableDatosCobranza.CUSCTYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSZPCNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSZPCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSZPCNull()
            Me(Me.tableDatosCobranza.CUSZPCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBRNNUMNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.BRNNUMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBRNNUMNull()
            Me(Me.tableDatosCobranza.BRNNUMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBRNNMENull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.BRNNMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBRNNMENull()
            Me(Me.tableDatosCobranza.BRNNMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBRNADRNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.BRNADRColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBRNADRNull()
            Me(Me.tableDatosCobranza.BRNADRColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBRNPHNNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.BRNPHNColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBRNPHNNull()
            Me(Me.tableDatosCobranza.BRNPHNColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLNCCNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLNCCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLNCCNull()
            Me(Me.tableDatosCobranza.DLNCCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLVCANull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLVCAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLVCANull()
            Me(Me.tableDatosCobranza.DLVCAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLVCMNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLVCMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLVCMNull()
            Me(Me.tableDatosCobranza.DLVCMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLVCDNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLVCDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLVCDNull()
            Me(Me.tableDatosCobranza.DLVCDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLCCYNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLCCYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLCCYNull()
            Me(Me.tableDatosCobranza.DLCCYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLEICNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLEICColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLEICNull()
            Me(Me.tableDatosCobranza.DLEICColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCIUDAGNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CIUDAGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCIUDAGNull()
            Me(Me.tableDatosCobranza.CIUDAGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPROVAGNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.PROVAGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPROVAGNull()
            Me(Me.tableDatosCobranza.PROVAGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDEPTAGNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DEPTAGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDEPTAGNull()
            Me(Me.tableDatosCobranza.DEPTAGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsHORAAGNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.HORAAGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetHORAAGNull()
            Me(Me.tableDatosCobranza.HORAAGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DataColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataNull()
            Me(Me.tableDatosCobranza.DataColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSFNANull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSFNAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSFNANull()
            Me(Me.tableDatosCobranza.CUSFNAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSLN1Null() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSLN1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSLN1Null()
            Me(Me.tableDatosCobranza.CUSLN1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSLN2Null() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSLN2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSLN2Null()
            Me(Me.tableDatosCobranza.CUSLN2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCUSSEXNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.CUSSEXColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCUSSEXNull()
            Me(Me.tableDatosCobranza.CUSSEXColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSIGN1NAMENull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.SIGN1NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSIGN1NAMENull()
            Me(Me.tableDatosCobranza.SIGN1NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSIGN2NAMENull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.SIGN2NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSIGN2NAMENull()
            Me(Me.tableDatosCobranza.SIGN2NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSIGN1POSITIONNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.SIGN1POSITIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSIGN1POSITIONNull()
            Me(Me.tableDatosCobranza.SIGN1POSITIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSIGN2POSITIONNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.SIGN2POSITIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSIGN2POSITIONNull()
            Me(Me.tableDatosCobranza.SIGN2POSITIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSIGN1DATANull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.SIGN1DATAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSIGN1DATANull()
            Me(Me.tableDatosCobranza.SIGN1DATAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSIGN2DATANull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.SIGN2DATAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSIGN2DATANull()
            Me(Me.tableDatosCobranza.SIGN2DATAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLEAENNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLEAENColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLEAENNull()
            Me(Me.tableDatosCobranza.DLEAENColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLEMENNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLEMENColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLEMENNull()
            Me(Me.tableDatosCobranza.DLEMENColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDLEDENNull() As Boolean
            Return Me.IsNull(Me.tableDatosCobranza.DLEDENColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDLEDENNull()
            Me(Me.tableDatosCobranza.DLEDENColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class DatosCobranzaRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As DatosCobranzaRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As DatosCobranzaRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As DatosCobranzaRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
